#include "market_data/optimized_market_data_handler.hpp"
#include "core/timer.hpp"
#include "core/logger.hpp"
#include <random>
#include <cstring>

namespace hft {
namespace market_data {

OptimizedMarketDataHandler::OptimizedMarketDataHandler() {
    // Pre-allocate order books for common symbols
    std::vector<std::string> common_symbols = {
        "AAPL", "GOOGL", "MSFT", "AMZN", "TSLA",
        "SPY", "QQQ", "IWM", "GLD", "TLT"
    };

    for (const auto& symbol : common_symbols) {
        order_books_[symbol] = std::make_unique<OrderBook>();
    }
}

OptimizedMarketDataHandler::~OptimizedMarketDataHandler() {
    stop();
}

void OptimizedMarketDataHandler::start() {
    if (running_.exchange(true)) {
        return;  // Already running
    }

    processing_thread_ = std::thread(&OptimizedMarketDataHandler::processingThread, this);
    LOG_INFO("Optimized market data handler started");
}

void OptimizedMarketDataHandler::stop() {
    if (running_.exchange(false)) {
        if (processing_thread_.joinable()) {
            processing_thread_.join();
        }
        LOG_INFO("Optimized market data handler stopped");
    }
}

void OptimizedMarketDataHandler::processMessage(const MarketDataMessage& msg) {
    // Add to batch buffer
    batch_buffer_[batch_count_++] = msg;

    // Process batch when full
    if (batch_count_ >= BATCH_SIZE) {
        processBatchInternal(batch_buffer_.data(), batch_count_);
        batch_count_ = 0;
    }
}

void OptimizedMarketDataHandler::processBatch(
    const std::vector<MarketDataMessage>& messages) {

    processBatchInternal(messages.data(), messages.size());
}

void OptimizedMarketDataHandler::processBatchZeroCopy(
    const MarketDataMessage* messages, size_t count) {

    processBatchInternal(messages, count);
}

const OrderBook* OptimizedMarketDataHandler::getOrderBook(
    const std::string& symbol) const {

    auto it = order_books_.find(symbol);
    return (it != order_books_.end()) ? it->second.get() : nullptr;
}

OrderBook* OptimizedMarketDataHandler::getOrderBook(const std::string& symbol) {
    auto it = order_books_.find(symbol);
    if (it != order_books_.end()) {
        return it->second.get();
    }

    // Create new order book for this symbol
    auto ob = std::make_unique<OrderBook>();
    auto* ptr = ob.get();
    order_books_[symbol] = std::move(ob);

    return ptr;
}

void OptimizedMarketDataHandler::subscribe(const std::string& symbol,
                                            MarketDataCallback callback) {
    callbacks_[symbol] = std::move(callback);
}

void OptimizedMarketDataHandler::processingThread() {
    // Batch processing buffer
    std::array<MarketDataMessage, BATCH_SIZE> batch;
    size_t batch_size = 0;

    while (running_ || !message_queue_.empty()) {
        // Try to fill batch from queue
        while (batch_size < BATCH_SIZE) {
            auto msg_opt = message_queue_.pop();
            if (!msg_opt.has_value()) {
                break;  // Queue empty
            }
            batch[batch_size++] = msg_opt.value();
        }

        // Process batch if we have messages
        if (batch_size > 0) {
            processBatchInternal(batch.data(), batch_size);
            batch_size = 0;
        } else {
            // Queue empty, sleep briefly
            std::this_thread::sleep_for(std::chrono::microseconds(1));
        }
    }
}

void OptimizedMarketDataHandler::processBatchInternal(
    const MarketDataMessage* messages, size_t count) {

    uint64_t batch_start = core::Timer::timestamp_ns();

    // Process each message in the batch
    for (size_t i = 0; i < count; ++i) {
        const auto& msg = messages[i];

        // Prefetch next message (cache optimization)
        if (i + 1 < count) {
            __builtin_prefetch(&messages[i + 1], 0, 3);
        }

        int64_t latency_ns = core::Timer::timestamp_ns() - msg.timestamp;

        OrderBook* ob = getOrderBook(msg.symbol);

        // Process message based on type
        switch (msg.type) {
            case MessageType::ORDER_ADD:
                ob->addOrder(msg.order);
                break;
            case MessageType::ORDER_MODIFY:
                ob->modifyOrder(msg.order.order_id, msg.order.quantity);
                break;
            case MessageType::ORDER_CANCEL:
                ob->cancelOrder(msg.order.order_id);
                break;
            case MessageType::TRADE:
                // Trades are generated by order book matching
                break;
            case MessageType::SNAPSHOT:
                // Handle snapshot (not implemented)
                break;
        }

        // Invoke callback if registered
        auto cb_it = callbacks_.find(msg.symbol);
        if (cb_it != callbacks_.end()) {
            cb_it->second(msg.symbol, *ob);
        }

        updateStatistics(latency_ns);
        messages_processed_.fetch_add(1, std::memory_order_relaxed);
    }

    batches_processed_.fetch_add(1, std::memory_order_relaxed);

    uint64_t batch_duration = core::Timer::timestamp_ns() - batch_start;

    if (count > 0) {
        LOG_DEBUG("Batch processed: ", count, " messages in ",
                  batch_duration / 1000, "μs (",
                  (batch_duration / count), "ns/msg)");
    }
}

void OptimizedMarketDataHandler::simdProcessPrices(const uint64_t* prices,
                                                    size_t count,
                                                    uint64_t* results) {
    // SIMD processing example using AVX2 (process 4 uint64_t at once)
    // This is a simplified example - real implementation would be more complex

#ifdef __AVX2__
    size_t simd_count = count & ~3;  // Round down to multiple of 4

    for (size_t i = 0; i < simd_count; i += 4) {
        // Load 4 prices
        __m256i price_vec = _mm256_loadu_si256(
            reinterpret_cast<const __m256i*>(&prices[i]));

        // Process (example: add constant)
        // In real use case, this could be computing mid-price, spreads, etc.

        // Store results
        _mm256_storeu_si256(reinterpret_cast<__m256i*>(&results[i]), price_vec);
    }

    // Handle remaining elements
    for (size_t i = simd_count; i < count; ++i) {
        results[i] = prices[i];
    }
#else
    // Fallback for non-AVX2 systems
    std::memcpy(results, prices, count * sizeof(uint64_t));
#endif
}

void OptimizedMarketDataHandler::updateStatistics(int64_t latency_ns) {
    // Exponential moving average with 95% weight on previous value
    uint64_t current_avg = avg_latency_ns_.load(std::memory_order_relaxed);
    uint64_t new_avg = (current_avg * 95 + latency_ns * 5) / 100;
    avg_latency_ns_.store(new_avg, std::memory_order_relaxed);
}

// Simulated Feed Implementation

OptimizedSimulatedFeed::OptimizedSimulatedFeed(
    OptimizedMarketDataHandler& handler)
    : handler_(handler) {}

void OptimizedSimulatedFeed::start() {
    if (running_.exchange(true)) {
        return;
    }

    feed_thread_ = std::thread(&OptimizedSimulatedFeed::feedThread, this);
    LOG_INFO("Optimized simulated feed started for symbol: ", symbol_);
}

void OptimizedSimulatedFeed::stop() {
    if (running_.exchange(false)) {
        if (feed_thread_.joinable()) {
            feed_thread_.join();
        }
        LOG_INFO("Optimized simulated feed stopped");
    }
}

void OptimizedSimulatedFeed::generateBurst(size_t message_count) {
    std::vector<MarketDataMessage> messages;
    messages.reserve(message_count);

    for (size_t i = 0; i < message_count; ++i) {
        messages.push_back(generateMessage());
    }

    // Send as batch
    handler_.processBatch(messages);

    LOG_INFO("Generated burst: ", message_count, " messages");
}

void OptimizedSimulatedFeed::feedThread() {
    std::random_device rd;
    std::mt19937 gen(rd());

    // Use batch generation for better performance
    constexpr size_t BATCH_SIZE = 64;
    std::vector<MarketDataMessage> batch;
    batch.reserve(BATCH_SIZE);

    while (running_) {
        // Generate batch
        batch.clear();
        for (size_t i = 0; i < BATCH_SIZE; ++i) {
            batch.push_back(generateMessage());
        }

        // Send batch
        handler_.processBatch(batch);

        // Sleep based on tick interval
        std::this_thread::sleep_for(
            std::chrono::microseconds(tick_interval_us_ * BATCH_SIZE));
    }
}

MarketDataMessage OptimizedSimulatedFeed::generateMessage() {
    static std::random_device rd;
    static std::mt19937 gen(rd());
    static std::uniform_int_distribution<> side_dist(0, 1);
    static std::uniform_int_distribution<> price_dist(9900, 10100);
    static std::uniform_int_distribution<> qty_dist(1, 100);
    static std::uniform_int_distribution<> action_dist(0, 100);

    MarketDataMessage msg;
    msg.timestamp = core::Timer::timestamp_ns();
    msg.symbol = symbol_;

    // 80% adds, 10% cancels, 10% modifies
    int action = action_dist(gen);

    if (action < 80) {
        msg.type = MessageType::ORDER_ADD;
        msg.order = Order{
            next_order_id_.fetch_add(1, std::memory_order_relaxed),
            static_cast<uint64_t>(price_dist(gen)),
            static_cast<uint32_t>(qty_dist(gen)),
            side_dist(gen) == 0 ? Side::BUY : Side::SELL,
            msg.timestamp
        };
    } else if (action < 90) {
        msg.type = MessageType::ORDER_CANCEL;
        uint64_t current_id = next_order_id_.load(std::memory_order_relaxed);
        msg.order.order_id = (current_id > 100) ? current_id - gen() % 100 : 1;
    } else {
        msg.type = MessageType::ORDER_MODIFY;
        uint64_t current_id = next_order_id_.load(std::memory_order_relaxed);
        msg.order.order_id = (current_id > 100) ? current_id - gen() % 100 : 1;
        msg.order.quantity = qty_dist(gen);
    }

    return msg;
}

} // namespace market_data
} // namespace hft
